<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>2.3.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>8</WarningLevel>
    <DefineConstants>$(DefineConstants);PRINT_LOG;PRINT_TIME</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>8</WarningLevel>
    <DefineConstants>$(DefineConstants);PRINT_LOG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call &quot;$(ProjectDir)packtarget.bat&quot; &quot;$(TargetDir)\&quot; &quot;$(AssemblyVersion)&quot;" />
  </Target>

</Project>